Use workdir/ as the application work directory
unikraft/catalog-core pull request #20
Opened 2024-12-01 12:42 UTC by razvand

For each application directory, user `workdir/` ad the application working directory.

Add the top-level `setup.sh` script to clone repositories in top-level `repos/` directory. Then use the per-application `setup.sh` to set up the `workdir/` directory accordingly.

Update per-application `Makefile` and `README.md` files to use `workdir/` and to instruct the use of the `setup.sh` script.

Update per-application `.gitignore` file to ignore `workdir/`.

2024-12-01 18:55 UTC, spx01 requested changes
Small typo present in each application's `README.md` and within the commit message itself

2024-12-01 18:55 UTC, spx01 commented on c-fs/README.md
> +1. Have your custom setup of repositories in the `workdir/` directory.
This paragraph should be numbered as `2.`

2024-12-01 18:55 UTC, spx01 commented on c-hello/README.md
> +1. Have your custom setup of repositories in the `workdir/` directory.
This paragraph should be numbered as `2.`

2024-12-01 18:55 UTC, spx01 commented on c-http/README.md
> +1. Have your custom setup of repositories in the `workdir/` directory.
This paragraph should be numbered as `2.`

2024-12-01 18:55 UTC, spx01 commented on cpp-hello/README.md
> +1. Have your custom setup of repositories in the `workdir/` directory.
This paragraph should be numbered as `2.`

2024-12-01 18:55 UTC, spx01 commented on elfloader-basic/README.md
> +1. Have your custom setup of repositories in the `workdir/` directory.
This paragraph should be numbered as `2.`

2024-12-01 18:55 UTC, spx01 commented on elfloader-net/README.md
> +1. Have your custom setup of repositories in the `workdir/` directory.
This paragraph should be numbered as `2.`

2024-12-01 18:55 UTC, spx01 commented on nginx/README.md
> +1. Have your custom setup of repositories in the `workdir/` directory.
This paragraph should be numbered as `2.`

2024-12-01 18:55 UTC, spx01 commented on python3-hello/README.md
> +1. Have your custom setup of repositories in the `workdir/` directory.
This paragraph should be numbered as `2.`

2024-12-07 16:24 UTC, razvand commented
> Small typo present in the commit message

@spx01 , what was the typo? Is it still there?

2024-12-07 16:43 UTC, spx01 commented
> > Small typo present in the commit message
> 
> @spx01 , what was the typo? Is it still there?

@razvand, apologies for not elaborating further to begin with, the typo is in `fe1e2ae`'s long message:
> For each application directory, user `workdir/` ad the application
working directory.

If the commits will be squashed, this may not need any consideration.

2024-12-09 13:51 UTC, StefanJum requested changes
Looks good, check the one comment.

2024-12-09 13:51 UTC, StefanJum commented on README.md
> +Instructions to install Docker are also part of the [Unikraft documentation]().
Add links here

2024-12-11 19:06 UTC, spx01 approved these changes

2024-12-16 20:44 UTC, spx01 approved these changes
Reviewed-by: spx01 <42381535+spx01@users.noreply.github.com>

2024-12-17 07:21 UTC, razvand commented on README.md
> +Instructions to install Docker are also part of the [Unikraft documentation]().
@StefanJum , solved.

2024-12-17 07:21 UTC, razvand commented
> > > Small typo present in the commit message
> > 
> > 
> > @spx01 , what was the typo? Is it still there?
> 
> @razvand, apologies for not elaborating further to begin with, the typo is in `fe1e2ae`'s long message:
> 
> > For each application directory, user `workdir/` ad the application
> > working directory.
> 
> If the commits will be squashed, this may not need any consideration.

@spx01 , solved

2024-12-17 14:06 UTC, StefanJum approved these changes
All good.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2024-12-17 16:46 UTC, spx01 approved these changes
Reviewed-by: spx01 42381535+spx01@users.noreply.github.com
Approved-by: spx01 42381535+spx01@users.noreply.github.com

2024-12-17 18:28 UTC, merged